# Generated by Django 5.0.2 on 2024-03-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bands',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='bands',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='bands',
            index=models.Index(fields=['-time_create'], name='bands_bands_time_cr_40bfe0_idx'),
        ),
    ]
