# Generated by Django 5.0.2 on 2024-06-03 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bands',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bands',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bands.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='bands',
            name='frontman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band', to='bands.frontman', verbose_name='Лидер группы'),
        ),
        migrations.AddField(
            model_name='bands',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='bands.tagpost', verbose_name='Тэги'),
        ),
    ]
