# Generated by Django 5.0.2 on 2024-03-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_alter_bands_options_bands_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bands',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
