# Generated by Django 5.0.2 on 2024-03-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_alter_bands_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bands',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
