# Generated by Django 5.0.2 on 2024-04-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_category_bands_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bands',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bands.category'),
        ),
    ]
