# Generated by Django 5.0.2 on 2024-05-09 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_frontman_m_count_alter_bands_frontman'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bands',
            options={'verbose_name': 'Core-группы', 'verbose_name_plural': 'Core-группы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveIndex(
            model_name='bands',
            name='bands_bands_time_cr_40bfe0_idx',
        ),
        migrations.AlterField(
            model_name='bands',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bands.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='bands',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='bands',
            name='frontman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band', to='bands.frontman', verbose_name='Лидер группы'),
        ),
        migrations.AlterField(
            model_name='bands',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bands',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bands',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='bands.tagpost', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='bands',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='bands',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='bands',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
    ]
